In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
import itertools
import pandas as pd
import numpy as np 
from math import log, exp
log(0.315245478)

-1.1544036484112792

In [2]:
from google.colab import drive
#Menyambungkan Ke drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
##SEED
SEED = 2022

In [6]:
data_normal = pd.read_csv('/content/gdrive/MyDrive/Skripsi/Data/data_normalized+Stopword.csv')

# TFIDF

In [8]:
texts = np.array(data_normal['steaming']) #text contents in dataframe to array for processing
vocab_length = len(list(itertools.chain.from_iterable(texts)))
print(len(texts))
print(vocab_length)

4354
730005


In [9]:
vectorize = TfidfVectorizer(use_idf=True)
response = vectorize.fit_transform(texts)
print(response)

  (0, 6550)	0.5515881726917298
  (0, 3315)	0.48605481069643547
  (0, 5369)	0.4774046469838137
  (0, 5397)	0.4481755283099634
  (0, 5499)	0.09581898118191344
  (0, 6158)	0.14677680488774894
  (1, 5617)	0.2905167792283078
  (1, 746)	0.2905167792283078
  (1, 5748)	0.16187517809889895
  (1, 5107)	0.3096171979356194
  (1, 6931)	0.3247780531781103
  (1, 5201)	0.22478823960321995
  (1, 1477)	0.08810175118568828
  (1, 4204)	0.13123524212055485
  (1, 3338)	0.1808161455207488
  (1, 2274)	0.2447582619178855
  (1, 4194)	0.37463300594588034
  (1, 475)	0.16898114972389938
  (1, 6427)	0.3247780531781103
  (1, 3150)	0.27294274673094415
  (1, 1253)	0.12538092613348356
  (1, 6354)	0.1746003921208206
  (1, 1111)	0.18546964513337555
  (1, 5499)	0.04251811125387342
  (1, 6158)	0.06512981501919116
  :	:
  (4352, 4204)	0.11992439879006982
  (4352, 5499)	0.03885357962860376
  (4353, 7000)	0.27293057289290434
  (4353, 6562)	0.2500839093693134
  (4353, 242)	0.24060168727361703
  (4353, 3327)	0.4355100475000521


In [10]:
response.shape

(4354, 7933)

In [11]:
feature_names = vectorize.get_feature_names()
print(len(feature_names))
print(response.todense())

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


7933
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [12]:
frame_tfidf = pd.DataFrame(response.todense().T,
                           index = vectorize.get_feature_names(),
                           columns= [f'D{ i + 1}' for i in range(len(texts))])

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [13]:
frame_tfidf

D1   D2   D3   D4   D5   D6   D7   D8   D9  D10  ...  D4345  \
aa          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
abadi       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
abai        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
abang       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
abas        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
...         ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   
zonasi      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
zone        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
zsexbwsyvr  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
zul         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
zura        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   

            D4346  D4347  D4348  D4349  D4350  D4351  D4352  D4353  D4354  
aa            0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
abadi         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
abai          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
abang         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
abas          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
...           ...    ...    ...    ...    ...    ...    ...    ...    ...  
zonasi        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
zone          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
zsexbwsyvr    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
zul           0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
zura          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[7933 rows x 4354 columns]

In [14]:
data_normal['tfidf'] = list(response.toarray())
vectors_for_training = np.array(data_normal['tfidf'].tolist())

In [15]:
vectors_for_training.shape

(4354, 7933)

In [16]:
vectors_for_training

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
labelencoder = LabelEncoder()
labels = np.array(labelencoder.fit_transform(data_normal['sentimen']).tolist())

# Train Test Split and Cross Validation

## Data Split

In [18]:
# Data Splitting & CV
from sklearn.model_selection import *
# Metrics
from sklearn.metrics import *

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(vectors_for_training, labels, test_size = 0.20, 
                                                      random_state = SEED)

In [20]:
print('Ukuran X Train:', X_train.shape)
print('Ukuran Y Train:', Y_train.shape)
print('Ukuran X Test:', X_test.shape)
print('Ukuran Y Test:', Y_test.shape)


Ukuran X Train: (3483, 7933)
Ukuran Y Train: (3483,)
Ukuran X Test: (871, 7933)
Ukuran Y Test: (871,)


## Cross Validation

In [21]:
cv = StratifiedKFold(n_splits = 5, shuffle = True,
                     random_state = SEED)

# Modelling 

In [22]:
from sklearn.naive_bayes import MultinomialNB

In [23]:
MNB = MultinomialNB()

In [24]:
params = {'alpha': [0.01, 0.1, 0.25, 0.75, 0.5, 0.025, 0.05, 0.075, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
         'fit_prior': [True, False],
         'class_prior': [None, [.37,.31, .32],[.4, .3, .3],[.35, .32, .33]]}

multinomial_nb_grid = GridSearchCV(MNB, param_grid=params, n_jobs=-1, cv=cv, verbose=5, scoring = 'accuracy')
multinomial_nb_grid.fit(X_train,Y_train)

Fitting 5 folds for each of 184 candidates, totalling 920 fits


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=2022, shuffle=True),
             estimator=MultinomialNB(), n_jobs=-1,
             param_grid={'alpha': [0.01, 0.1, 0.25, 0.75, 0.5, 0.025, 0.05,
                                   0.075, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9,
                                   0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08,
                                   0.09],
                         'class_prior': [None, [0.37, 0.31, 0.32],
                                         [0.4, 0.3, 0.3], [0.35, 0.32, 0.33]],
                         'fit_prior': [True, False]},
             scoring='accuracy', verbose=5)

In [25]:
print('Train Accuracy : %.3f'%multinomial_nb_grid.best_estimator_.score(X_train, Y_train))
print('Test Accuracy : %.3f'%multinomial_nb_grid.best_estimator_.score(X_test, Y_test))
print('Best Accuracy Through Grid Search : %.3f'%multinomial_nb_grid.best_score_)
print('Best Parameters : ',multinomial_nb_grid.best_params_)

Train Accuracy : 0.884
Test Accuracy : 0.714
Best Accuracy Through Grid Search : 0.697
Best Parameters :  {'alpha': 0.4, 'class_prior': None, 'fit_prior': False}


In [26]:
MNB1 = MultinomialNB(alpha=0.4, class_prior=None, fit_prior= False )

In [27]:
scores = cross_val_score(MNB1, X_train, Y_train,  n_jobs=-1, cv=cv, verbose=5, scoring = 'accuracy')
print(scores)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.


[0.71449067 0.70014347 0.68579627 0.69252874 0.69396552]


[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    1.0s finished


In [28]:
Coba = MNB1.fit(X_train, Y_train)

In [31]:
hasil = Coba.predict(X_train)
accuracy_score(Y_train, hasil)

0.8840080390467987

In [32]:
MNB1.class_count_

array([1285., 1098., 1100.])

In [33]:
MNB1.feature_count_.T

array([[0.        , 0.        , 0.30463826],
       [0.        , 1.17207883, 0.        ],
       [1.34606108, 0.        , 2.06456764],
       ...,
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.21886128],
       [0.        , 0.        , 0.27624271]])

In [34]:
frame_fit1 = pd.DataFrame(MNB1.feature_count_.T,
                           index = vectorize.get_feature_names(),
                           columns= MNB1.classes_)
frame_fit1

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


0         1         2
aa          0.000000  0.000000  0.304638
abadi       0.000000  1.172079  0.000000
abai        1.346061  0.000000  2.064568
abang       0.335788  0.335788  0.647097
abas        0.316596  0.000000  0.349878
...              ...       ...       ...
zonasi      0.000000  0.000000  0.257569
zone        0.000000  0.310507  0.000000
zsexbwsyvr  0.000000  0.000000  0.000000
zul         0.000000  0.000000  0.218861
zura        0.000000  0.000000  0.276243

[7933 rows x 3 columns]

In [35]:
 positif = frame_fit1[1].sum()
 negatif = frame_fit1[0].sum()
 netral = frame_fit1[2].sum()

print('Positif:', positif)
print('Negatif:', negatif)
print('Netral:', netral)

Positif: 3523.210133629251
Negatif: 4794.045800792696
Netral: 4292.507571233053


In [36]:
exponen = exp(-9.899384873143688	)
atas1 = 1- (negatif*exponen)
hasil_aa = atas1/exponen
hasil_aa

15124.068701189019

In [38]:
frame_fit = pd.DataFrame(MNB1.feature_log_prob_.T,
                           index = vectorize.get_feature_names(),
                           columns= MNB1.classes_)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [39]:
frame_fit

0         1         2
aa         -9.899385 -9.725618 -9.268146
abadi      -9.899385 -8.356928 -9.834366
abai       -8.425732 -9.725618 -8.016059
abang      -9.289907 -9.116140 -8.872054
abas       -9.316337 -9.725618 -9.205920
...              ...       ...       ...
zonasi     -9.899385 -9.725618 -9.337280
zone       -9.899385 -9.151103 -9.834366
zsexbwsyvr -9.899385 -9.725618 -9.834366
zul        -9.899385 -9.725618 -9.397950
zura       -9.899385 -9.725618 -9.309279

[7933 rows x 3 columns]

In [41]:
hasil2 = Coba.predict(X_test)
accuracy_score(Y_test, hasil2)

0.7141216991963261

In [42]:
confusion_matrix(Y_test, hasil2)

array([[262,  49,  34],
       [ 61, 157,  39],
       [ 42,  24, 203]])

In [45]:
MNB1.class_count_

array([1285., 1098., 1100.])